### ISSUE TITLE
the  software can't run normally,catch Exception!

### ISSUE THREAD

**Issue by luoshuichao** [lqomg/mdvideo#1]
![image](https://user-images.githubusercontent.com/66509517/182011771-fff938ec-7745-4aff-a9c9-d3081360d37a.png)

**Comment by lqomg** [comment]
> ![image](https://user-images.githubusercontent.com/66509517/182011771-fff938ec-7745-4aff-a9c9-d3081360d37a.png)

见： https://mdvideo.wvovw.com/guide/what-is-wvovw.html

1.x版本已不在维护
