### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Hao4Wang** [lqomg/mdvideo#3]
1. [Awesome Marp：一整套自定义 Marp 主题](https://github.com/favourhong/Awesome-Marp) 国内网友制作的PPT模板，可否添加到MdVideo.
2. [精选技术周刊信息流](https://www.fre123.com/weekly/) 搜罗不少分享类周刊，你可以通过〖开源自荐〗推广本项目。此外，微博平台的互联网博主也接收自荐分享，例如@宝玉xp，@爱可可-爱生活，@互联网的那点事，@GitHubDaily，@蚁工厂。

**Comment by lqomg** [comment]
@Hao4Wang  
1. 我抽时间看一下这个，感觉它生成的ppt还很好看的，我会尝试默认有个类似的主题，比如如PPT转视频?
2. 但我目前并不太想推广这个项目，因为它还有很多不足，放在阮老师周刊也是看看有没有人使用，现在看来效果还可以，等它稳定一些了我在推广。非常感谢你提供的这些渠道！！！
