### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Hao4Wang** [lqomg/mdvideo#4]
1. 下载“素材资料包.zip”，解压需要密码；
2. 想要自制包.zip，能否告知文件格式排版？
3. 今天看到一个[新项目](https://github.com/YaoFANGUK/video-subtitle-remover)，README.md 最后展示着它的开源赞助信息。你的这个项目创意很好，为何不公开赞助渠道。
4. [paper2gui](https://github.com/Baiyuetribe/paper2gui) 这个项目揉合了不少小组件，感觉其中一二可以添加到工作台。

**Comment by lqomg** [comment]
@Hao4Wang  
1. 不需要密码的，直接把压缩包拖拽进去就可以了
2. 后期加个需求让用户可以自定义文件排版
3. 没必要，目前就300多个用户，没啥人愿意给的 哈哈
4. 谢谢，Mark了
