### ISSUE TITLE
bug: the specified module could not be found

### ISSUE THREAD

**Issue by yuanyxh** [lqomg/mdvideo#5]
## Bugs

运行程序出现：the specified module could not be found，无法加载 canvas.node module，路径前多了 `\\?\`

![Snipaste_2024-02-24_18-43-44](https://github.com/lqomg/mdvideo/assets/72425622/d565c283-7c93-45ad-bece-92ae0c701e3f)

系统：windows10 x64

**Comment by lqomg** [comment]
> ## Bugs
> 运行程序出现：the specified module could not be found，无法加载 canvas.node module，路径前多了 `\\?\`
> 
> ![Snipaste_2024-02-24_18-43-44](https://private-user-images.githubusercontent.com/72425622/307514970-d565c283-7c93-45ad-bece-92ae0c701e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjA2MDMsIm5iZiI6MTcwOTg2MDMwMywicGF0aCI6Ii83MjQyNTYyMi8zMDc1MTQ5NzAtZDU2NWMyODMtN2M5My00NWFkLWJlY2UtOTJhZTBjNzAxZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDAxMTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMGFjYzg1YjdhMTYxMWZmYTVlMThmNGQwYmNlMTI0ZDIyNDcxOTg3NGJjZTc1ZDJmZjBjOGRhOWU1YTg4MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LjosQGbsozfmxeNTopt3vNLE7lsn7KqY5fhdI2Qurog)
> 
> 系统：windows10 x64


注意事项，需要安装Visual Studio 2010
[https://mdvideo.wvovw.com/guide/download.html](https://mdvideo.wvovw.com/guide/download.html)
